[versions]

assertj = "3.27.3"
dependency-analysis-gradle-plugin = "2.10.0"
jetbrains-annotations = "23.0.0"
jackson = "2.18.2"
jackson-kogera = "2.18.2-beta17"
jakarta-inject = "2.0.1"
junit = "5.12.0"
jvm-dependency-conflict-resolution = "2.1.2"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
kotlinx-datetime = "0.6.2"
log4j = "2.24.1"
log4j-kotlin = "1.5.0"
mockk = "1.13.17"
spring = "6.2.3"
spring-boot = "3.4.3"
spring-mockk = "4.0.2"
versions-gradle-plugin = "0.52.0"

[libraries]

[libraries.assertj]
module = "org.assertj:assertj-core"
version.ref = "assertj"

[libraries.dependency-analysis-gradle-plugin-dependency]
module = "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin"
version.ref = "dependency-analysis-gradle-plugin"

[libraries.jackson-bom]
module = "com.fasterxml.jackson:jackson-bom"
version.ref = "jackson"

[libraries.jackson-module-kogera]
module = "com.github.ProjectMapK:jackson-module-kogera"
version.ref = "jackson-kogera"

[libraries.jackson-module-kotlin]
module = "com.fasterxml.jackson.module:jackson-module-kotlin"

[libraries.jakarta-inject]
module = "jakarta.inject:jakarta.inject-api"
version.ref = "jakarta-inject"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.junit-api]
module = "org.junit.jupiter:junit-jupiter-api"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit"

[libraries.junit-params]
module = "org.junit.jupiter:junit-jupiter-params"

[libraries.jvm-dependency-conflict-resolution-gradle-plugin-dependency]
module = "org.gradlex:jvm-dependency-conflict-resolution"
version.ref = "jvm-dependency-conflict-resolution"

[libraries.kotlin-gradle-plugin-dependency]
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlin-spring-gradle-plugin-dependency]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.kotlinx-coroutines-bom]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.kotlinx-coroutines-core-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"

[libraries.kotlinx-coroutines-reactor]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor"

[libraries.kotlinx-coroutines-test]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"

[libraries.kotlinx-coroutines-test-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm"

[libraries.kotlinx-datetime]
module = "org.jetbrains.kotlinx:kotlinx-datetime"
version.ref = "kotlinx-datetime"

[libraries.kotlinx-datetime-jvm]
module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm"
version.ref = "kotlinx-datetime"

[libraries.log4j-api]
module = "org.apache.logging.log4j:log4j-api"

[libraries.log4j-bom]
module = "org.apache.logging.log4j:log4j-bom"
version.ref = "log4j"

[libraries.log4j-core]
module = "org.apache.logging.log4j:log4j-core"

[libraries.log4j-api-kotlin]
module = "org.apache.logging.log4j:log4j-api-kotlin"
version.ref = "log4j-kotlin"

[libraries.log4j-slf4j2-impl]
module = "org.apache.logging.log4j:log4j-slf4j2-impl"
version.ref = "log4j-kotlin"

[libraries.mockk]
module = "io.mockk:mockk"
version.ref = "mockk"

[libraries.mockk-dsl]
module = "io.mockk:mockk-dsl"
version.ref = "mockk"

[libraries.mockk-dsl-jvm]
module = "io.mockk:mockk-dsl-jvm"
version.ref = "mockk"

[libraries.spring]
module = "org.springframework:spring"

[libraries.spring-beans]
module = "org.springframework:spring-beans"

[libraries.spring-bom]
module = "org.springframework:spring-framework-bom"
version.ref = "spring"

[libraries.spring-context]
module = "org.springframework:spring-context"

[libraries.spring-core]
module = "org.springframework:spring-core"

[libraries.spring-mockk]
module = "com.ninja-squad:springmockk"
version.ref = "spring-mockk"

[libraries.spring-test]
module = "org.springframework:spring-test"

[libraries.spring-web]
module = "org.springframework:spring-web"

[libraries.springboot]
module = "org.springframework.boot:spring-boot"

[libraries.springboot-autoconfigure]
module = "org.springframework.boot:spring-boot-autoconfigure"

[libraries.springboot-bom]
module = "org.springframework.boot:spring-boot-dependencies"
version.ref = "spring-boot"

[libraries.springboot-gradle-plugin-dependency]
module = "org.springframework.boot:spring-boot-gradle-plugin"
version.ref = "spring-boot"

[libraries.springboot-starter]
module = "org.springframework.boot:spring-boot-starter"

[libraries.springboot-starter-json]
module = "org.springframework.boot:spring-boot-starter-json"

[libraries.springboot-starter-log4j2]
module = "org.springframework.boot:spring-boot-starter-log4j2"

[libraries.springboot-starter-test]
module = "org.springframework.boot:spring-boot-starter-test"

[libraries.springboot-starter-webflux]
module = "org.springframework.boot:spring-boot-starter-webflux"

[libraries.springboot-test]
module = "org.springframework.boot:spring-boot-test"

[libraries.springboot-test-autoconfigure]
module = "org.springframework.boot:spring-boot-test-autoconfigure"

[bundles]

kotlinx-coroutines-jvm = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm",
]

kotlinx-coroutines-reactor = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm",
	"kotlinx-coroutines-reactor",
]

kotlinx-coroutines-test-jvm = [
	"kotlinx-coroutines-test",
	"kotlinx-coroutines-test-jvm",
]

kotlinx-datetime-jvm = [
	"kotlinx-datetime",
	"kotlinx-datetime-jvm",
]

log4j-kotlin = [
	"log4j-api",
	"log4j-api-kotlin",
]

mockk-jvm = [
	"mockk",
	"mockk-dsl",
	"mockk-dsl-jvm",
]

[plugins]

[plugins.dependency-analysis-gradle-plugin]
id = "com.autonomousapps.dependency-analysis"
version.ref = "dependency-analysis-gradle-plugin"

[plugins.kotlin-gradle-plugin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.jvm-dependency-conflict-detection-gradle-plugin]
id = "org.gradlex.jvm-dependency-conflict-detection"
version.ref = "jvm-dependency-conflict-resolution"

[plugins.jvm-dependency-conflict-resolution-gradle-plugin]
id = "org.gradlex.jvm-dependency-conflict-resolution"
version.ref = "jvm-dependency-conflict-resolution"

[plugins.springboot-plugin]
id = "org.springframework.boot"
version.ref = "spring-boot"

[plugins.versions-gradle-plugin]
id = "com.github.ben-manes.versions"
version.ref = "versions-gradle-plugin"
