[versions]

assertj = "3.23.1"
equalsverifier = "3.11.1"
jetbrains-annotations = "23.0.0"
junit = "5.9.1"
kotlin = "1.7.21"
kotlinx-coroutines = "1.6.4"
kotlinx-datetime = "0.4.0"
mockk = "1.13.2"
slf4j = "2.0.5"
spring = "6.0.2"
spring-boot = "3.0.0"

[libraries]

[libraries.assertj]
module = "org.assertj:assertj-core"
version.ref = "assertj"

[libraries.equalsverifier]
module = "nl.jqno.equalsverifier:equalsverifier"
version.ref = "equalsverifier"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit"

[libraries.kotlin-gradle-plugin-dependency]
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlin-spring-gradle-plugin-dependency]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.kotlinx-coroutines-bom]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-test]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-test-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-datetime-jvm]
module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm"
version.ref = "kotlinx-datetime"

[libraries.mockk]
module = "io.mockk:mockk"
version.ref = "mockk"

[libraries.mockk-dsl-jvm]
module = "io.mockk:mockk-dsl-jvm"
version.ref = "mockk"

[libraries.slf4j-simple]
module = "org.slf4j:slf4j-simple"
version.ref = "slf4j"

[libraries.spring-boot-bom]
module = "org.springframework.boot:spring-boot-dependencies"
version.ref = "spring-boot"

[libraries.spring-boot-gradle-plugin-dependency]
module = "org.springframework.boot:spring-boot-gradle-plugin"
version.ref = "spring-boot"

[libraries.spring-boot-starter]
module = "org.springframework.boot:spring-boot-starter"
version.ref = "spring-boot"

[libraries.spring-boot-starter-test]
module = "org.springframework.boot:spring-boot-starter-test"
version.ref = "spring-boot"

[libraries.spring-boot-starter-webflux]
module = "org.springframework.boot:spring-boot-starter-webflux"
version.ref = "spring-boot"

[libraries.spring-context]
module = "org.springframework:spring-context"
version.ref = "spring"

[bundles]

kotlinx-coroutines-jvm = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm"
]

kotlinx-coroutines-test-jvm = [
	"kotlinx-coroutines-test",
	"kotlinx-coroutines-test-jvm"
]

mockk-jvm = ["mockk", "mockk-dsl-jvm"]

[plugins]

[plugins.kotlin-gradle-plugin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.spring-boot-plugin]
id = "org.springframework.boot"
version.ref = "spring-boot"
