[versions]

assertj = "3.24.2"
dependency-analysis-gradle-plugin = "1.24.0"
equalsverifier = "3.11.1"
jetbrains-annotations = "23.0.0"
jackson = "2.15.2"
jackson-kogera = "2.15.2-beta4"
jakarta-inject = "2.0.1"
junit = "5.10.0" # Duplicated in unit-test-suite.gradle.kts.
kotlin = "1.9.10" # See also `kotlinTargetVersion` in kotlin-project.gradle.kts.
kotlinx-coroutines = "1.7.3"
kotlinx-datetime = "0.4.1"
log4j = "2.20.0"
log4j-kotlin = "1.2.0"
mockk = "1.13.8"
spring = "6.1.0-M5"
spring-boot = "3.2.0-M3"
spring-mockk = "4.0.2"
versions-gradle-plugin = "0.48.0"

[libraries]

[libraries.assertj]
module = "org.assertj:assertj-core"
version.ref = "assertj"

[libraries.dependency-analysis-gradle-plugin-dependency]
module = "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin"
version.ref = "dependency-analysis-gradle-plugin"

[libraries.equalsverifier]
module = "nl.jqno.equalsverifier:equalsverifier"
version.ref = "equalsverifier"

[libraries.jackson-bom]
module = "com.fasterxml.jackson:jackson-bom"
version.ref = "jackson"

[libraries.jackson-module-kogera]
module = "com.github.ProjectMapK:jackson-module-kogera"
version.ref = "jackson-kogera"

[libraries.jackson-module-kotlin]
module = "com.fasterxml.jackson.module:jackson-module-kotlin"
version.ref = "jackson"

[libraries.jakarta-inject]
module = "jakarta.inject:jakarta.inject-api"
version.ref = "jakarta-inject"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit"

[libraries.kotlin-gradle-plugin-dependency]
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlin-spring-gradle-plugin-dependency]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.kotlinx-coroutines-bom]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-reactor]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-test]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-test-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-datetime]
module = "org.jetbrains.kotlinx:kotlinx-datetime"
version.ref = "kotlinx-datetime"

[libraries.kotlinx-datetime-jvm]
module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm"
version.ref = "kotlinx-datetime"

[libraries.log4j-api]
module = "org.apache.logging.log4j:log4j-api"
version.ref = "log4j"

[libraries.log4j-bom]
module = "org.apache.logging.log4j:log4j-bom"
version.ref = "log4j"

[libraries.log4j-core]
module = "org.apache.logging.log4j:log4j-core"
version.ref = "log4j"

[libraries.log4j-api-kotlin]
module = "org.apache.logging.log4j:log4j-api-kotlin"
version.ref = "log4j-kotlin"

[libraries.log4j-slf4j2-impl]
module = "org.apache.logging.log4j:log4j-slf4j2-impl"
version.ref = "log4j-kotlin"

[libraries.mockk]
module = "io.mockk:mockk"
version.ref = "mockk"

[libraries.mockk-dsl]
module = "io.mockk:mockk-dsl"
version.ref = "mockk"

[libraries.mockk-dsl-jvm]
module = "io.mockk:mockk-dsl-jvm"
version.ref = "mockk"

[libraries.spring]
module = "org.springframework:spring"
version.ref = "spring"

[libraries.spring-beans]
module = "org.springframework:spring-beans"
version.ref = "spring"

[libraries.spring-boot]
module = "org.springframework.boot:spring-boot"
version.ref = "spring-boot"

[libraries.spring-boot-autoconfigure]
module = "org.springframework.boot:spring-boot-autoconfigure"
version.ref = "spring-boot"

[libraries.spring-boot-bom]
module = "org.springframework.boot:spring-boot-dependencies"
version.ref = "spring-boot"

[libraries.spring-boot-gradle-plugin-dependency]
module = "org.springframework.boot:spring-boot-gradle-plugin"
version.ref = "spring-boot"

[libraries.spring-boot-starter]
module = "org.springframework.boot:spring-boot-starter"
version.ref = "spring-boot"

[libraries.spring-boot-starter-json]
module = "org.springframework.boot:spring-boot-starter-json"
version.ref = "spring-boot"

[libraries.spring-boot-starter-log4j2]
module = "org.springframework.boot:spring-boot-starter-log4j2"
version.ref = "spring-boot"

[libraries.spring-boot-starter-test]
module = "org.springframework.boot:spring-boot-starter-test"
version.ref = "spring-boot"

[libraries.spring-boot-starter-webflux]
module = "org.springframework.boot:spring-boot-starter-webflux"
version.ref = "spring-boot"

[libraries.spring-boot-test]
module = "org.springframework.boot:spring-boot-test"
version.ref = "spring-boot"

[libraries.spring-boot-test-autoconfigure]
module = "org.springframework.boot:spring-boot-test-autoconfigure"
version.ref = "spring-boot"

[libraries.spring-context]
module = "org.springframework:spring-context"
version.ref = "spring"

[libraries.spring-core]
module = "org.springframework:spring-core"
version.ref = "spring"

[libraries.spring-mockk]
module = "com.ninja-squad:springmockk"
version.ref = "spring-mockk"

[libraries.spring-test]
module = "org.springframework:spring-test"
version.ref = "spring"

[libraries.spring-web]
module = "org.springframework:spring-web"
version.ref = "spring"

[bundles]

kotlinx-coroutines-jvm = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm",
]

kotlinx-coroutines-reactor = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm",
	"kotlinx-coroutines-reactor",
]

kotlinx-coroutines-test-jvm = [
	"kotlinx-coroutines-test",
	"kotlinx-coroutines-test-jvm",
]

kotlinx-datetime-jvm = [
	"kotlinx-datetime",
	"kotlinx-datetime-jvm",
]

log4j-kotlin = [
	"log4j-api",
	"log4j-api-kotlin",
]

mockk-jvm = [
	"mockk",
	"mockk-dsl",
	"mockk-dsl-jvm",
]

[plugins]

[plugins.dependency-analysis-gradle-plugin]
id = "com.autonomousapps.dependency-analysis"
version.ref = "dependency-analysis-gradle-plugin"

[plugins.kotlin-gradle-plugin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.spring-boot-plugin]
id = "org.springframework.boot"
version.ref = "spring-boot"

[plugins.versions-gradle-plugin]
id = "com.github.ben-manes.versions"
version.ref = "versions-gradle-plugin"
