[versions]

assertj = "3.27.3"
dependencyAnalysis-gradlePlugin = "2.19.0"
jetbrains-annotations = "23.0.0"
jackson = "2.19.2"
jackson-kogera = "2.19.2-beta27"
jakarta-inject = "2.0.1"
junit = "5.13.4"
jvmDependencyConflictResolution-gradlePlugin = "2.4"
kotlin = "2.2.0"
kotlin-metadata-jvm = "2.2.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.0"
log4j = "2.25.1"
log4j-kotlin = "1.5.0"
mockk = "1.14.4"
osdetector-gradlePlugin = "1.7.3"
spring = "6.2.9"
spring-boot = "3.5.4"
spring-mockk = "4.0.2"
versionsCheck-gradlePlugin = "0.52.0"

[libraries]

[libraries.assertj]
module = "org.assertj:assertj-core"
version.ref = "assertj"

[libraries.dependencyAnalysis-gradlePluginDependency]
module = "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin"
version.ref = "dependencyAnalysis-gradlePlugin"

[libraries.jackson-bom]
module = "com.fasterxml.jackson:jackson-bom"
version.ref = "jackson"

[libraries.jackson-module-kogera]
module = "com.github.ProjectMapK:jackson-module-kogera"
version.ref = "jackson-kogera"

[libraries.jackson-module-kotlin]
module = "com.fasterxml.jackson.module:jackson-module-kotlin"

[libraries.jakarta-inject]
module = "jakarta.inject:jakarta.inject-api"
version.ref = "jakarta-inject"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.junit-api]
module = "org.junit.jupiter:junit-jupiter-api"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit"

[libraries.junit-params]
module = "org.junit.jupiter:junit-jupiter-params"

[libraries.jvmDependencyConflictResolution-gradlePluginDependency]
module = "org.gradlex:jvm-dependency-conflict-resolution"
version.ref = "jvmDependencyConflictResolution-gradlePlugin"

[libraries.kotlin-gradlePluginDependency]
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"
version.ref = "kotlin"

[libraries.kotlin-spring-gradlePluginDependency]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.kotlin-metadata-jvm]
module = "org.jetbrains.kotlin:kotlin-metadata-jvm"
version.ref = "kotlin-metadata-jvm"

[libraries.kotlinx-coroutines-bom]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom"
version.ref = "kotlinx-coroutines"

[libraries.kotlinx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.kotlinx-coroutines-core-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"

[libraries.kotlinx-coroutines-reactor]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor"

[libraries.kotlinx-coroutines-test]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"

[libraries.kotlinx-coroutines-test-jvm]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm"

[libraries.kotlinx-datetime]
module = "org.jetbrains.kotlinx:kotlinx-datetime"
version.ref = "kotlinx-datetime"

[libraries.kotlinx-datetime-jvm]
module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm"
version.ref = "kotlinx-datetime"

[libraries.log4j-api]
module = "org.apache.logging.log4j:log4j-api"

[libraries.log4j-bom]
module = "org.apache.logging.log4j:log4j-bom"
version.ref = "log4j"

[libraries.log4j-core]
module = "org.apache.logging.log4j:log4j-core"

[libraries.log4j-api-kotlin]
module = "org.apache.logging.log4j:log4j-api-kotlin"
version.ref = "log4j-kotlin"

[libraries.log4j-slf4j2-impl]
module = "org.apache.logging.log4j:log4j-slf4j2-impl"
version.ref = "log4j-kotlin"

[libraries.mockk]
module = "io.mockk:mockk"
version.ref = "mockk"

[libraries.mockk-dsl]
module = "io.mockk:mockk-dsl"
version.ref = "mockk"

[libraries.mockk-dsl-jvm]
module = "io.mockk:mockk-dsl-jvm"
version.ref = "mockk"

[libraries.osdetector-gradlePluginDependency]
module = "com.google.gradle:osdetector-gradle-plugin"
version.ref = "osdetector-gradlePlugin"

[libraries.spring]
module = "org.springframework:spring"

[libraries.spring-beans]
module = "org.springframework:spring-beans"

[libraries.spring-bom]
module = "org.springframework:spring-framework-bom"
version.ref = "spring"

[libraries.spring-context]
module = "org.springframework:spring-context"

[libraries.spring-core]
module = "org.springframework:spring-core"

[libraries.spring-mockk]
module = "com.ninja-squad:springmockk"
version.ref = "spring-mockk"

[libraries.spring-test]
module = "org.springframework:spring-test"

[libraries.spring-web]
module = "org.springframework:spring-web"

[libraries.springboot]
module = "org.springframework.boot:spring-boot"

[libraries.springboot-autoconfigure]
module = "org.springframework.boot:spring-boot-autoconfigure"

[libraries.springboot-bom]
module = "org.springframework.boot:spring-boot-dependencies"
version.ref = "spring-boot"

[libraries.springboot-gradlePluginDependency]
module = "org.springframework.boot:spring-boot-gradle-plugin"
version.ref = "spring-boot"

[libraries.springboot-starter]
module = "org.springframework.boot:spring-boot-starter"

[libraries.springboot-starter-json]
module = "org.springframework.boot:spring-boot-starter-json"

[libraries.springboot-starter-log4j2]
module = "org.springframework.boot:spring-boot-starter-log4j2"

[libraries.springboot-starter-test]
module = "org.springframework.boot:spring-boot-starter-test"

[libraries.springboot-starter-webflux]
module = "org.springframework.boot:spring-boot-starter-webflux"

[libraries.springboot-test]
module = "org.springframework.boot:spring-boot-test"

[libraries.springboot-test-autoconfigure]
module = "org.springframework.boot:spring-boot-test-autoconfigure"

[libraries.versionsCheck-gradlePluginDependency]
module = "com.github.ben-manes:gradle-versions-plugin"
version.ref = "versionsCheck-gradlePlugin"

[bundles]

kotlinx-coroutines-jvm = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm",
]

kotlinx-coroutines-reactor = [
	"kotlinx-coroutines-core",
	"kotlinx-coroutines-core-jvm",
	"kotlinx-coroutines-reactor",
]

kotlinx-coroutines-test-jvm = [
	"kotlinx-coroutines-test",
	"kotlinx-coroutines-test-jvm",
]

kotlinx-datetime-jvm = [
	"kotlinx-datetime",
	"kotlinx-datetime-jvm",
]

log4j-kotlin = [
	"log4j-api",
	"log4j-api-kotlin",
]

mockk-jvm = [
	"mockk",
	"mockk-dsl",
	"mockk-dsl-jvm",
]

[plugins]

[plugins.dependencyAnalysis-gradlePlugin]
id = "com.autonomousapps.dependency-analysis"
version.ref = "dependencyAnalysis-gradlePlugin"

[plugins.kotlin-gradlePlugin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.jvmDependencyConflictDetection-gradlePlugin]
id = "org.gradlex.jvm-dependency-conflict-detection"
version.ref = "jvmDependencyConflictResolution-gradlePlugin"

[plugins.jvmDependencyConflictResolution-gradlePlugin]
id = "org.gradlex.jvm-dependency-conflict-resolution"
version.ref = "jvmDependencyConflictResolution-gradlePlugin"

[plugins.osdetector-gradlePlugin]
id = "com.google.osdetector"
version.ref = "osdetector-gradlePlugin"

[plugins.springboot-gradlePlugin]
id = "org.springframework.boot"
version.ref = "spring-boot"

[plugins.versionsCheck-gradlePlugin]
id = "com.github.ben-manes.versions"
version.ref = "versionsCheck-gradlePlugin"
